services:
  backend:
  build: .
  container_name: backend
  env_file: .env
  ports:
    - "8080:8080"
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started
  networks:
    - app-network
  command: sh -c "
    npx drizzle-kit migrate:dev &&
    npm run start"

  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: revision
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge